name = "qwert"
main = "src/worker.ts"
compatibility_date = "2023-05-28"

# # Durable Object binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/durable-objects
# [[durable_objects]]
# binding = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"

# # Bucket binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/kv#bucket
# [[buckets]]
# binding = "MY_BUCKET"
# name = "my-bucket"
# bucket_id = "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"

# # Service binding - For more information: https://developers.cloudflare.com/workers/platform/services
# [[routes]]
# binding = "MY_SERVICE"
# pattern = "/api/*"
# script = "api.js"

# # Queue binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/queues
# [[queues]]
# binding = "MY_QUEUE"
# name = "my-queue"
# zone_id = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"

# # KV Namespace binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/kv
kv_namespaces=[
    { binding = "qwertKV", id = "77251eebf5884136a0d61e6ef5348984", preview_id = "1b92191772f0491aac4baeb0a8c52e50" }
]

# [env.shared]
# SHARED_VARIABLE = "shared_value"
