version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "/app/app.db" # Database file inside the container
    volumes:
      - app_data:/app # Mount a volume to persist the SQLite database

volumes:
  app_data: