[package]
name = "egui"
version = "0.1.0"
authors = ["gongbaodd@Inspiron_PS <gongbaodd@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.18.0"
