FROM ghcr.io/cirruslabs/android-sdk:33

USER root

# RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add - \
#     && echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list \
#     && apt-get update

RUN apt-get update && apt install clang cmake ninja-build pkg-config libgtk-3-dev fonts-liberation libu2f-udev libvulkan1 xdg-utils -y


ENV flutter_version=stable

ENV FLUTTER_HOME=${HOME}/sdks/flutter \
    FLUTTER_VERSION=$flutter_version
ENV FLUTTER_ROOT=$FLUTTER_HOME

ENV PATH ${PATH}:${FLUTTER_HOME}/bin:${FLUTTER_HOME}/bin/cache/dart-sdk/bin

RUN rm -Rf ${FLUTTER_HOME}

RUN git clone --depth 1 --branch ${FLUTTER_VERSION} https://gitee.com/mirrors/Flutter.git ${FLUTTER_HOME}

RUN yes | flutter doctor --android-licenses \
    && flutter doctor \
    && chown -R root:root ${FLUTTER_HOME}

ENV FLUTTER_GIT_URL=https://gitee.com/mirrors/Flutter.git

CMD ["/bin/bash"]   